name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - main
      - DSG-actions
  release:
    types: [published]  # Triggers when a GitHub Release is published
  workflow_dispatch:  # Allow manual runs if needed

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      #id-token: write  # (needed for OIDC auth)

    steps:

      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up variables
        id: vars
        run: |
          if [ "${{ github.event_name }}" = "release" ]; then
            echo "IMAGE_TAG=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
          else
            SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
            echo "IMAGE_TAG=${SHORT_SHA}" >> $GITHUB_ENV
          fi

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./deploy/Dockerfile
          push: false
          tags: ${{ vars.ECR_REGISTRY }}/${{ vars.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}

  promote-to-manifest:
    needs: build-and-push
    runs-on: ubuntu-latest
    permissions:
      contents: write  ## to allow committing changes
    steps:
      - name: Checkout manifest repo
        uses: actions/checkout@v4
        with:
          repository: leaf-ai/manifest
          token: ${{ secrets.READ_WRITE_PAT_FOR_DEPLOYMENT }}
          ref: main 

      - name: Update image tag in values.yaml
        run: |
          #sed -i 's/tag: .*/tag: ${{ github.sha }}/' path/to/values.yaml
          python ./manifest/neuro-ai/utility_scripts/deploy_to_cluster.sh

      #- name: Commit and push changes
      #  run: |
      #    git config user.name "GitHub Actions"
      #    git config user.email "actions@github.com"
      #    git add path/to/values.yaml
      #    git commit -m "Update image tag to ${{ github.sha }}"
      #    git push







