name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - main
      - DSG-actions
  release:
    types: [published]  # Triggers when a GitHub Release is published
  workflow_dispatch:  # Allow manual runs if needed

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.set-vars.outputs.image_tag }}
      target_environment: ${{ steps.set-vars.outputs.target_environment }}

    permissions:
      contents: read
      #id-token: write  # (needed for OIDC auth)

    steps:

      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up variables
        id: set-vars
        run: |
          if [ "${{ github.event_name }}" = "release" ]; then
            echo "image_tag=${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT
            echo "target_environment=staging" >> $GITHUB_OUTPUT
          else
            SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
            echo "image_tag=${SHORT_SHA}" >> $GITHUB_OUTPUT
            echo "target_environment=dev" >> $GITHUB_OUTPUT
          fi

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./deploy/Dockerfile
          push: false
          tags: ${{ vars.ECR_REGISTRY }}/${{ vars.ECR_REPOSITORY }}:${{ steps.set-vars.outputs.image_tag }}

  promote-to-manifest:
    needs: build-and-push
    runs-on: ubuntu-latest
    permissions:
      contents: write  ## to allow committing changes
    steps:
      - name: Checkout manifest repo
        uses: actions/checkout@v4
        with:
          repository: leaf-ai/manifest
          token: ${{ secrets.READ_WRITE_PAT_FOR_DEPLOYMENT }}
          ref: main 

      - name: Update image tag in values.yaml
        run: |
          echo "Set IMAGE_TAG to ${{ needs.build-and-push.outputs.image_tag }}"
          echo "Set ENVIRONMENT to ${{ needs.build-and-push.outputs.target_environment }}"

          python neuro-san/utility_scripts/deploy_to_cluster.py \
          --file-path "neuro-san/values-${{ needs.build-and-push.outputs.target_environment }}.yaml" \
          --neuro-san-tag "${{ needs.build-and-push.outputs.image_tag }}"

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add "neuro-san/values-${{ needs.build-and-push.outputs.target_environment }}.yaml"
          git commit -m "Update image tag to ${{ github.sha }}"
          git push







